Auto-Clean_Temp = true

[ai]
api_key = "your-openai-api-key-here"
model = {thinkmodel = "deepseek-reasoner", chatmodel = "deepseek-chat"}
base_url = "https://api.deepseek.com"
max_history_items = 15
system_prompt = ""

[record]
FORMAT = "pyaudio.paInt16"  # 音频格式
CHANNELS = 1  # 通道数
RATE = 44100  # 采样率
CHUNK = 1024  # 采样块大小
RECORD_SECONDS = 5  # 录音时长
SILENCE_THRESHOLD = 90  # 静音阈值(DB)
SILENCE_DURATION = 2.0   # 静音持续时间（秒）后停止
MAX_DURATION = 30.0      # 最大录音时长（秒），防止无限录音
SAVE_PATH = "./tmp" # 保存路径
DEFAULT_SPT_MODEL_PATH = ""
mono_save_path = "./mono"